// frontend/src/pages/AdminPage.jsx
import { useEffect, useState } from "react";
import DataTable from "../components/DataTable";

export default function AdminPage() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetch("/api/admin/users")
      .then((res) => res.json())
      .then((data) => setUsers(data));
  }, []);

  const columns = [
    { key: "id", title: "ID" },
    { key: "name", title: "Имя" },
    { key: "email", title: "Email" },
    { key: "role", title: "Роль" },
  ];

  return (
    <div style={{ padding: "20px" }}>
      <h1>Admin panel</h1>
      <DataTable columns={columns} data={users} />
    </div>
  );
}

// frontend/src/pages/AdminPage.vue
<script setup>
import DataTable from "@/components/DataTable.vue";
import { ref, onMounted } from "vue";
import axios from "axios";

const columns = ["id", "name", "email", "role"];
const users = ref([]);

onMounted(async () => {
  const { data } = await axios.get("/api/users");
  users.value = data.users;
});
</script>

<template>
  <div>
    <h1>Admin panel</h1>

    <DataTable :columns="columns" :rows="users" />
  </div>
</template>
