// frontend/src/pages/InventoryPage.vue
<script setup>
import { ref, onMounted } from "vue";
import axios from "axios";
import DataTable from "@/components/DataTable.vue";

const items = ref([]);

const columns = ["id", "name", "category", "price", "count"];

onMounted(async () => {
  const { data } = await axios.get("/api/inventories");
  items.value = data.inventories;
});
</script>

<template>
  <div>
    <h1>Inventory for all</h1>

    <DataTable :columns="columns" :rows="items" />
  </div>
</template>

// frontend/src/pages/InventoryPage.jsx
import { useEffect, useState } from "react";
import DataTable from "../components/DataTable";

export default function InventoryPage() {
  const [items, setItems] = useState([]);

  useEffect(() => {
    fetch("/api/inventories")
      .then((res) => res.json())
      .then((data) => setItems(data));
  }, []);

  const columns = [
    { key: "id", title: "ID" },
    { key: "name", title: "Название" },
    { key: "category", title: "Категория" },
    { key: "count", title: "Количество" },
  ];

  return (
    <div style={{ padding: "20px" }}>
      <h1>Inventory for all</h1>
      <DataTable columns={columns} data={items} />
    </div>
  );
}
